// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, created_at, updated_at, email)
VALUES (
    id = gen_random_uuid(),
    created_at = NOW(),
    updated_at = NOW(),
    email = $1
)
RETURNING id, created_at, updated_st, email
`

func (q *Queries) CreateUser(ctx context.Context, email sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedSt,
		&i.Email,
	)
	return i, err
}
